#!/bin/bash
# WF 2018-09-08
# create fat jar and copy it to release directory
# recompile skip tests and signing
mvn -U clean install  -D skipTests -D gpg.skip -D createRelease=true -D createAssembly=true
